include:
  - project: "whoer/cicd-templates"
    ref: master
    file:
      - "00-default-vars.yml"
      - "10-lint-templates.yml"
      - "10-build-templates.yml"
      - "10-update_service-templates.yml"

variables:
  UPDATE_SERVICE_WEBHOOK_URL_PROD: "https://193.108.118.249:9443/api/webhooks/db7966dc-e6dd-4b13-a8f2-b1f70a06bea5"

stages:
  - lint
  - build
  - test
  - deploy
  - update_service

Lint Dockerfile:
  extends: .lint_dockerfile
  variables:
    DOCKERFILE_PATH: "${CI_PROJECT_DIR}/Dockerfile"

Build whox-blog-backend:
  extends: .build_dockerfile_template
  variables:
    CI_REGISTRY_IMAGE: "whox-blog-backend"
    BUILD_CONTEXT_DIR: "${CI_PROJECT_DIR}"
    BUILD_DOCKERFILE_PATH: "${CI_PROJECT_DIR}/Dockerfile"

#Deploy Update Service - stage:
#  stage: update_service
#  image:
#    name: curlimages/curl:8.8.0
#  script:
#    - curl -k -X POST  ${UPDATE_SERVICE_WEBHOOK_URL_STAGE}
#  #rules:
#  #  - if: $CI_COMMIT_TAG
#  #when: manual
#  #allow_failure: false    

Update Service - whox-blog-backend-prod:
  stage: update_service
  image:
    name: curlimages/curl:8.8.0
  script:
    - curl -k -X POST  ${UPDATE_SERVICE_WEBHOOK_URL_PROD}
  #rules:
  #  - if: $CI_COMMIT_TAG
  #when: manual
  #allow_failure: false